name: Deploy and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy to Vercel
      - name: Deploy to Vercel
        run: vercel --prod -y

      # Get deployment URL
      - name: Get Deployment URL
        run: |
          DEPLOYMENT_URL=$(vercel alias ls | awk '{print $3}')
          echo "Deployment URL: $DEPLOYMENT_URL"
          echo "##[set-output name=deployment_url;]$DEPLOYMENT_URL"

      # Set output for deployment URL
      - name: Set Deployment URL Output
        id: set_deployment_url
        run: echo "::set-output name=deployment_url::$DEPLOYMENT_URL"

  test:
    runs-on: ubuntu-latest
    needs: deploy
    env:
      CYPRESS_BASE_URL: ${{ needs.deploy.outputs.deployment_url }}
      NODE_VERSION: 20.7.0

    steps:
      - name: Use Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies and checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.before }}

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:run
